// Phase F Step F7: small pixel-art sprite the kiosk renders next to
// a step's body when the step has an ``action_slot`` set AND the
// activity has at least one toy. The component is intentionally
// minimal — it is a passive ``<img>`` with an ``onError``-hides-element
// path so a 404 (capability disabled, generation not yet finished,
// generation failed) renders as "no sprite for this step" rather than
// a broken image. The kiosk's body text reads the same as today in
// that case.
//
// Mounting URL: ``/api/static/images/toy_actions/<toy_id>/<slot>.{webp,png}``.
// Phase U: tries .webp first (animated sprite if generated by batch_animate.py),
// falls back to .png on 404 (static sprite from the image-gen worker).
// Phase V: CSS slot-entry intro animation state machine. Initial render
// uses .png while the intro animation plays. After animationend fires for
// the idle slot, format switches to .webp for the steady-state animated
// sprite. Non-idle slots stay on .png after their intro completes.
// The static-files mount lives at ``/api/static/images`` (see
// ``src/toybox/app.py``).
//
// Accessibility: the ``alt`` attribute is mandatory — toybox is
// family-facing and the F8 parent grid will reuse this component, so
// a11y is not optional. When ``toyDisplayName`` is provided the alt is
// ``"<display_name> <slot>"`` (e.g. "Mr. Unicorn looking"); otherwise
// it falls back to the bare slot key.

import { useEffect, useRef, useState } from "react";
import type { CSSProperties, JSX } from "react";

// CSS module import — Vite transforms CSS modules natively; data-animating
// attribute selectors in the .module.css file target the img element without
// class-name mangling. The import below ensures Vite processes the file during
// both dev and test runs (vitest uses Vite transforms).
import "./ToyActionSprite.module.css";

// Map of slot → CSS animation name (informational; actual animation targeting
// is done via the data-animating attribute in the CSS module above).
export const SLOT_INTRO_ANIMATIONS: Record<string, string> = {
  idle: "fadeIn",
  pointing: "slideInLeft",
  looking: "tiltIn",
  jumping: "bounceUp",
  cheering: "bounceWiggle",
  thinking: "floatIn",
  waving: "swingIn",
  running: "slideInFast",
  sleeping: "slowFadeIn",
  confused: "wobbleIn",
};

type SpriteFormat = "webp" | "png" | "hidden";

export interface ToyActionSpriteProps {
  // UUID of the toy whose sprite to fetch. Combined with ``slot`` to
  // form the static-files URL. The component does NOT validate the
  // shape; bad input simply produces a 404 the ``onError`` path hides.
  toyId: string;
  // One of the 10 ACTION_SLOTS members (e.g. "looking", "jumping",
  // "idle"). Component is permissive about the value — any string is
  // accepted because the URL is the source of truth and a bad slot
  // surfaces as a 404 the ``onError`` handler hides.
  slot: string;
  // Optional toy display name for accessibility. When present the alt
  // is "<display_name> <slot>"; otherwise alt is the bare slot key.
  toyDisplayName?: string;
  // Pixel size for the rendered sprite. Defaults to 112 px — sits in
  // the plan's 96-128 px design band. The kiosk uses the default; the
  // F8 parent grid will pass a smaller value for the cell size.
  size?: number;
  // Optional style override merged onto the default. Lets parent
  // layouts adjust margin / flex behavior without re-deriving the
  // base pixel-art presentation rules.
  style?: CSSProperties;
  // Optional cache-bust query value. When set, the sprite URL becomes
  // ``<base>?v=<encodeURIComponent(cacheKey)>`` so a regenerated
  // on-disk PNG at the same path renders the new bytes instead of the
  // browser-cached bitmap. Used by the parent ToyActionGrid (threads
  // ``row.seed``); the kiosk omits it (no cache-bust needed there).
  cacheKey?: string;
}

export function ToyActionSprite(props: ToyActionSpriteProps): JSX.Element | null {
  const size = props.size ?? 112;

  // Phase V: animatingSlot drives the data-animating attribute.
  // Non-null = intro animation is playing; null = animation complete.
  // Using state (not ref) so setting it triggers the re-render needed
  // to add/remove the data-animating attribute from the DOM element.
  const [animatingSlot, setAnimatingSlot] = useState<string | null>(props.slot);

  // Ref tracking which slot was animating when the intro started.
  // Guards against the stale-closure race where slot changes mid-animation:
  // if the img's onAnimationEnd fires after a slot prop change, the handler
  // reads the ref (set at effect time) rather than the potentially-stale
  // closure over props.slot.
  const animatingSlotRef = useRef<string | null>(props.slot);

  // Phase V: initial render uses .png while intro animation plays.
  // After animationend fires for the idle slot, switches to .webp
  // for the steady-state animated sprite. Non-idle slots stay on .png.
  const [format, setFormat] = useState<SpriteFormat>("png");

  // On slot-prop change (and mount — slot is in the dep array): restart
  // the intro animation. Reset format back to png for the new slot.
  useEffect(() => {
    animatingSlotRef.current = props.slot;
    setAnimatingSlot(props.slot);
    setFormat("png");
  }, [props.slot]);

  if (format === "hidden") return null;

  const alt =
    props.toyDisplayName !== undefined && props.toyDisplayName.length > 0
      ? `${props.toyDisplayName} ${props.slot}`
      : props.slot;

  const baseStyle: CSSProperties = {
    width: size,
    height: size,
    flexShrink: 0,
    objectFit: "contain",
    background: "transparent",
  };
  const merged: CSSProperties = { ...baseStyle, ...(props.style ?? {}) };

  const baseUrl = `/api/static/images/toy_actions/${props.toyId}/${props.slot}.${format}`;
  const src =
    props.cacheKey !== undefined
      ? `${baseUrl}?v=${encodeURIComponent(props.cacheKey)}`
      : baseUrl;

  // Phase V: onAnimationEnd clears the animating state, then if the
  // completed slot was "idle" transitions format to "webp" for the
  // steady-state animated sprite. Non-idle slots keep .png after intro
  // completes. Reading from the ref (not props.slot) avoids a
  // stale-closure race: if the slot prop changes mid-animation the ref
  // still holds the slot that actually started animating.
  const handleAnimationEnd = () => {
    const completedSlot = animatingSlotRef.current;
    animatingSlotRef.current = null;
    setAnimatingSlot(null);
    if (completedSlot === "idle") {
      setFormat("webp");
    }
  };

  // Phase U / Phase V: WebP fallback chain fires only during idle
  // steady state (after intro animation completes for idle slot and
  // format has been set to "webp"). During the intro animation phase
  // the format is always "png" so this only triggers on real 404s.
  const handleError = () => {
    if (format === "webp") {
      setFormat("png");
    } else {
      setFormat("hidden");
    }
  };

  return (
    <img
      data-testid="toy-action-sprite"
      data-slot={props.slot}
      data-toy-id={props.toyId}
      data-animating={animatingSlot ?? undefined}
      src={src}
      alt={alt}
      width={size}
      height={size}
      onAnimationEnd={handleAnimationEnd}
      onError={handleError}
      style={merged}
    />
  );
}
