// AUTOGENERATED from src/toybox/core/errors.py — do not edit by hand.
// Regenerate with `python tools/gen_types_ts.py`.
export const ErrorCode = {
  lan_bind_requires_pin: "lan_bind_requires_pin",
  invalid_display_name: "invalid_display_name",
  version_conflict: "version_conflict",
  ws_backpressure_drop: "ws_backpressure_drop",
  upload_too_large: "upload_too_large",
  unsupported_image_type: "unsupported_image_type",
} as const;

export type ErrorCode = typeof ErrorCode[keyof typeof ErrorCode];
