// AUTOGENERATED from Pydantic models + Role enum — do not edit by hand.
// Regenerate with `python tools/gen_types_ts.py`.
//
// Phase G G1: until the pydantic2ts pipeline (gated on the json2ts
// Node CLI) is wired up, the per-module fallback in
// ``tools/gen_types_ts.py`` writes this file deterministically from
// the Pydantic models in ``src/toybox/activities/models.py`` and
// the Role taxonomy in ``src/toybox/activities/roles.py``. The
// shapes below MUST stay in sync with those modules — the kiosk's
// ChoiceButton (Phase G G4) imports ``Choice`` from here, and the
// parent UI imports ``RoleName`` / ``ROLE_DISPLAY_NAMES`` for the
// per-toy role restriction control.

/**
 * Phase G template-time choice — ONE branch in a step's
 * ``choices`` list. ``next`` is the successor step id authored in
 * the template JSON. The KIOSK does not consume this shape directly
 * — the API serializer transforms ``activity_steps.choices_json``
 * (a JSON array of pre-rendered label strings) into the runtime
 * ``{label, choice_index}`` shape kiosks render.
 */
export interface Choice {
  label: string;
  next: string;
}

/**
 * Phase G template-time step definition. Optional fields ``id`` /
 * ``next`` / ``choices`` are additive — pre-Phase-G linear
 * templates leave all three null and rely on the implicit edge
 * rule (advance to next array position).
 *
 * The runtime activity-step shape (one row in ``activity_steps``,
 * what the kiosk receives over WS / REST) is intentionally NOT
 * this interface — the runtime form has ``seq``, ``body``,
 * ``current``, and a different ``choices`` shape carrying
 * ``{label, choice_index}``. See ``frontend/src/child/api.ts``
 * for the runtime ``ActivityStep``; this interface is for
 * tooling that authors / inspects template JSON.
 */
export interface Step {
  text: string;
  sfx?: string | null;
  expected_action?: string | null;
  action_slot?: string | null;
  id?: string | null;
  next?: string | null;
  choices?: Choice[] | null;
  element_id?: string | null;
}

/**
 * Per-toy role restriction taxonomy — derived at codegen time
 * from ``src/toybox/activities/roles.py``. The single source of
 * truth is the Python ``Role`` enum; do not hand-edit either
 * the union below or ``ROLE_DISPLAY_NAMES``.
 */
export type RoleName = "big_bad_boss" | "boss_mini_boss" | "frenemy" | "friend" | "guide_mentor" | "helper_townsperson" | "needs_saving" | "quest_giver" | "sidekick" | "trickster";

/**
 * Title-cased display strings keyed by ``RoleName`` for the
 * parent UI's role-restriction control.
 */
export const ROLE_DISPLAY_NAMES: Record<RoleName, string> = {
  big_bad_boss: "Big Bad Boss",
  boss_mini_boss: "Boss / Mini-Boss",
  frenemy: "Frenemy",
  friend: "Friend",
  guide_mentor: "Guide / Mentor",
  helper_townsperson: "Helper / Townsperson",
  needs_saving: "Needs Saving",
  quest_giver: "Quest Giver",
  sidekick: "Sidekick",
  trickster: "Trickster",
};

/**
 * Phase N N2 template-type taxonomy — derived at codegen
 * time from the ``TemplateType`` Literal alias in
 * ``src/toybox/activities/models.py``. Templates that omit
 * the field round-trip as ``null``; templates that set it
 * activate the matching structural validator gate in
 * ``src/toybox/activities/_validator.py``. The frontend
 * (Phase O) reads this typed field rather than a freeform
 * string so ``categorize()`` cannot drift from the Python
 * source.
 */
export type TemplateType = "element_microgame";

/**
 * Phase L L1 picture-reward animation taxonomy — derived at
 * codegen time from the ``Animation`` StrEnum in
 * ``src/toybox/activities/models.py``. Order is member-
 * definition order (NOT alphabetical) so the parent UI's
 * RewardsList animation dropdown renders the six options in
 * the spec order.
 */
export type Animation = "shine" | "jump" | "spin" | "pulse" | "wobble" | "float";

/**
 * Phase L L1 per-activity reward type — derived at codegen
 * time from the ``RewardType`` Literal alias in
 * ``src/toybox/activities/models.py``. The parent's approve
 * dropdown and the kiosk's reward-step renderer both branch
 * on these four wire strings.
 */
export type RewardType = "picture" | "joke" | "song" | "random" | "none";
