// AUTOGENERATED from Pydantic models — do not edit by hand.
// Regenerate with `python tools/gen_types_ts.py`.
//
// Phase G G1: until the pydantic2ts pipeline (gated on the json2ts
// Node CLI) is wired up, the per-module fallback in
// ``tools/gen_types_ts.py`` writes this file deterministically from
// the Pydantic models in ``src/toybox/activities/models.py``. The
// shapes below MUST stay in sync with that module — the kiosk's
// ChoiceButton (Phase G G4) imports ``Choice`` from here, and the
// activity-step response shape extends with a ``choices`` field
// that carries the runtime ``{label, choice_index}`` form derived
// from ``activity_steps.choices_json`` (see Phase G plan
// §"How choices reach the kiosk").

/**
 * Phase G template-time choice — ONE branch in a step's
 * ``choices`` list. ``next`` is the successor step id authored in
 * the template JSON. The KIOSK does not consume this shape directly
 * — the API serializer transforms ``activity_steps.choices_json``
 * (a JSON array of pre-rendered label strings) into the runtime
 * ``{label, choice_index}`` shape kiosks render.
 */
export interface Choice {
  label: string;
  next: string;
}

/**
 * Phase G template-time step definition. Optional fields ``id`` /
 * ``next`` / ``choices`` are additive — pre-Phase-G linear
 * templates leave all three null and rely on the implicit edge
 * rule (advance to next array position).
 *
 * The runtime activity-step shape (one row in ``activity_steps``,
 * what the kiosk receives over WS / REST) is intentionally NOT
 * this interface — the runtime form has ``seq``, ``body``,
 * ``current``, and a different ``choices`` shape carrying
 * ``{label, choice_index}``. See ``frontend/src/child/api.ts``
 * for the runtime ``ActivityStep``; this interface is for
 * tooling that authors / inspects template JSON.
 */
export interface Step {
  text: string;
  sfx?: string | null;
  expected_action?: string | null;
  action_slot?: string | null;
  id?: string | null;
  next?: string | null;
  choices?: Choice[] | null;
}
