"""Generate ``frontend/src/shared/errors.ts`` from ``toybox.core.errors.ErrorCode``.

Case 2 fallback (per Phase A Step 1 spike): the upstream ``pydantic2ts``
package depends on the ``json2ts`` Node CLI for emission, which is not
guaranteed to be installed on every workstation. This script side-steps
that by walking the StrEnum directly and writing a deterministic TS file.

Output shape::

    // AUTOGENERATED ...
    export const ErrorCode = {
      lan_bind_requires_pin: "lan_bind_requires_pin",
      ...
    } as const;
    export type ErrorCode = typeof ErrorCode[keyof typeof ErrorCode];

Usage::

    python tools/gen_error_codes_ts.py
"""

from __future__ import annotations

import sys
from enum import EnumType
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "src"))

from toybox.core.errors import ErrorCode  # noqa: E402

OUTPUT_PATH = REPO_ROOT / "frontend" / "src" / "shared" / "errors.ts"

HEADER = (
    "// AUTOGENERATED from src/toybox/core/errors.py — do not edit by hand.\n"
    "// Regenerate with `python tools/gen_types_ts.py`.\n"
)


def render_typescript(error_code_class: EnumType = ErrorCode) -> str:
    """Return the TypeScript text for the given StrEnum.

    Pure function: no I/O, no module-level state mutation. Determinism is
    guaranteed by iterating the enum in declaration order (Python ``Enum``
    preserves the order members were defined in the class body).

    See ``tests/unit/test_gen_error_codes_ts.py`` for the determinism +
    drift gate that pins this contract.
    """
    lines: list[str] = [HEADER, "export const ErrorCode = {\n"]
    for member in error_code_class:
        # Member name and value are intentionally identical (see errors.py).
        lines.append(f'  {member.name}: "{member.value}",\n')
    lines.append("} as const;\n\n")
    lines.append("export type ErrorCode = typeof ErrorCode[keyof typeof ErrorCode];\n")
    return "".join(lines)


def main() -> int:
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    rendered = render_typescript(ErrorCode)
    OUTPUT_PATH.write_text(rendered, encoding="utf-8", newline="\n")
    print(f"wrote {OUTPUT_PATH.relative_to(REPO_ROOT)} ({len(ErrorCode)} members)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
