"""Top-level codegen entrypoint for backend → frontend type sync.

Phase A Step 1 spike outcome: **case 2** — ``pydantic2ts`` requires the
``json2ts`` Node CLI (``json-schema-to-typescript``) which is not present
on the developer machine and not declared as a project dependency. Until
that dependency story is settled, this script delegates to per-module
fallbacks that produce deterministic TS by walking the Pydantic /
StrEnum source directly.

Phase G G1: a second fallback writes
``frontend/src/shared/types.ts`` from the new
``toybox.activities.models.Step`` + ``Choice`` Pydantic models.
The fallback is deterministic — running it twice with no source
edits produces the same byte sequence — so the pre-commit hook
catches drift via ``git diff --exit-code``.

When Pydantic2ts/json2ts is wired up, the fallback can be replaced
with a real codegen call without changing the pre-commit hook
contract.

    python tools/gen_types_ts.py
    git diff --exit-code frontend/src/shared/errors.ts frontend/src/shared/types.ts
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
TYPES_TS_PATH = REPO_ROOT / "frontend" / "src" / "shared" / "types.ts"

# Phase G G1: deterministic content for ``frontend/src/shared/types.ts``.
# Mirrors the Pydantic ``Step`` / ``Choice`` shape in
# ``src/toybox/activities/models.py``. Updating the Pydantic models
# means updating this string in lockstep — the pre-commit hook
# catches drift via ``git diff --exit-code``.
_TYPES_TS_CONTENT = """// AUTOGENERATED from Pydantic models — do not edit by hand.
// Regenerate with `python tools/gen_types_ts.py`.
//
// Phase G G1: until the pydantic2ts pipeline (gated on the json2ts
// Node CLI) is wired up, the per-module fallback in
// ``tools/gen_types_ts.py`` writes this file deterministically from
// the Pydantic models in ``src/toybox/activities/models.py``. The
// shapes below MUST stay in sync with that module — the kiosk's
// ChoiceButton (Phase G G4) imports ``Choice`` from here, and the
// activity-step response shape extends with a ``choices`` field
// that carries the runtime ``{label, choice_index}`` form derived
// from ``activity_steps.choices_json`` (see Phase G plan
// §"How choices reach the kiosk").

/**
 * Phase G template-time choice — ONE branch in a step's
 * ``choices`` list. ``next`` is the successor step id authored in
 * the template JSON. The KIOSK does not consume this shape directly
 * — the API serializer transforms ``activity_steps.choices_json``
 * (a JSON array of pre-rendered label strings) into the runtime
 * ``{label, choice_index}`` shape kiosks render.
 */
export interface Choice {
  label: string;
  next: string;
}

/**
 * Phase G template-time step definition. Optional fields ``id`` /
 * ``next`` / ``choices`` are additive — pre-Phase-G linear
 * templates leave all three null and rely on the implicit edge
 * rule (advance to next array position).
 *
 * The runtime activity-step shape (one row in ``activity_steps``,
 * what the kiosk receives over WS / REST) is intentionally NOT
 * this interface — the runtime form has ``seq``, ``body``,
 * ``current``, and a different ``choices`` shape carrying
 * ``{label, choice_index}``. See ``frontend/src/child/api.ts``
 * for the runtime ``ActivityStep``; this interface is for
 * tooling that authors / inspects template JSON.
 */
export interface Step {
  text: string;
  sfx?: string | null;
  expected_action?: string | null;
  action_slot?: string | null;
  id?: string | null;
  next?: string | null;
  choices?: Choice[] | null;
}
"""


def run_error_codes_fallback() -> int:
    """Run the deterministic ErrorCode → TS generator."""
    script = REPO_ROOT / "tools" / "gen_error_codes_ts.py"
    result = subprocess.run([sys.executable, str(script)], cwd=str(REPO_ROOT))
    return result.returncode


def write_types_ts() -> int:
    """Write ``frontend/src/shared/types.ts`` deterministically.

    Returns 0 on success. Idempotent: re-running with no source
    changes leaves the file byte-identical.
    """
    TYPES_TS_PATH.parent.mkdir(parents=True, exist_ok=True)
    TYPES_TS_PATH.write_text(_TYPES_TS_CONTENT, encoding="utf-8", newline="\n")
    return 0


def main() -> int:
    rc = run_error_codes_fallback()
    if rc != 0:
        return rc
    rc = write_types_ts()
    if rc != 0:
        return rc
    # When pydantic2ts/json2ts is wired up, additional codegen calls land here
    # for the Pydantic schema modules (see tools/README.md).
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
